**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



## creation of N-D array

In [3]:
import numpy as na

In [6]:
# 1)at creating
array1 = na.array([1,2,3,4,5,6,7,8,9,10,11,12,14,13,15],ndmin = 3)
print(array1)
array1.ndim

[[ 1  2  3  4  5  6  7  8  9 10 11 12 14 13 15]]


2

In [9]:
# using reshape
array1 = na.array([1,2,3,4,5,6,7,8,9,10,11,12,14,13,15]).reshape(1,3,5)
array1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 14, 13, 15]]])

In [12]:
# using square brackets
array1 = na.array([[[1,2,3,4,5,6,7,8,9,10,11,12,14,13,15]]])
array1.ndim
print(array1)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 14 13 15]]]


In [15]:
array1 = na.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin = 4)
print(array1)
array1.ndim

[[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]


4

In [17]:
arr = na.random.rand(1,20)
arr

array([[0.92159191, 0.1800372 , 0.2752481 , 0.85169667, 0.73043214,
        0.10472116, 0.37340943, 0.12623971, 0.49601778, 0.92158508,
        0.3399594 , 0.65873984, 0.24964266, 0.26601582, 0.62111942,
        0.09437062, 0.32734622, 0.76544195, 0.74433759, 0.97223977]])

### ARRAY SLICING AND INDEXING

In [41]:
arr = na.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr2 = na.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]).reshape(1,3,3)
arr2

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [42]:
arr[3]

73

In [45]:
arr2[0][2,1]

7

In [49]:
arr[0:5]

array([ 0, 11, 26, 73, 42])

In [55]:
 arr2[0][1:3,0:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [57]:
arr[1:8:2]

array([11, 73, 51, 77])

### Data Type Manipulation

In [69]:
int_array = na.array([1, 2, 3, 4, 5])
int_array.dtype

dtype('int32')

In [67]:
int_array = na.array([1, 2, 3, 4, 5],dtype = "int16")
int_array.dtype

dtype('int16')

In [68]:
float_array = na.array([0.1, 0.2, 0.3, 0.4, 0.5])
float_array.dtype

dtype('float64')

In [70]:
int_array = na.array([1, 2, 3, 4, 5])
int_array.astype("float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [72]:
float_array = na.array([0.1, 0.2, 0.3, 0.4, 0.5])
float_array.astype("int32")

array([0, 0, 0, 0, 0])

### Generating Random Numbers:

In [74]:
rand_integers = na.random.randint(0,100,10)
rand_integers

array([23, 48, 72, 56, 20, 25, 10, 52, 73, 84])

In [77]:
rand_uniform = na.random.uniform(-1,1,5)
rand_uniform

array([ 0.51771226,  0.82536512,  0.79501086, -0.29408402, -0.94710724])

In [81]:
rand_matrix = na.random.randint(50,100,16)
rand_matrix

array([61, 97, 50, 76, 72, 55, 61, 62, 53, 90, 58, 65, 53, 93, 87, 82])

In [82]:
rand_matrix.reshape(4,4)

array([[61, 97, 50, 76],
       [72, 55, 61, 62],
       [53, 90, 58, 65],
       [53, 93, 87, 82]])

In [83]:
# measure of central tendency
rand_matrix.mean() # mean of array

69.6875

In [84]:
na.median(rand_matrix) # median

63.5

In [86]:
na.max(rand_matrix)
na.min(rand_matrix)
range = na.max(rand_matrix) - na.min(rand_matrix)
range

47

In [87]:
# to find the outlier we use IQR
q1 = na.percentile(rand_matrix,25)
q3 = na.percentile(rand_matrix,75)
IQR = q3 - q1
IQR

26.0

In [88]:
lower = q1 - (1.5*IQR)
lower

18.25

In [89]:
upper = q3 + (1.5*IQR)
upper

122.25

In [91]:
rand_matrix[rand_matrix>upper]

array([], dtype=int32)

In [92]:
rand_matrix[rand_matrix<lower]

array([], dtype=int32)

### Analyze the Data:

In [93]:
Salaries =na.array( [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [94]:
len(Salaries<50000)

30

In [99]:
na.median(Salaries)

61699.5

In [102]:
range = Salaries.max() - Salaries.min()
range

3082388

In [108]:
na.percentile(Salaries,25)

52963.25

In [109]:
na.percentile(Salaries,75)

84496.5

In [123]:
arr = Salaries[Salaries<52963.25]
arr

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [124]:
arr2 = Salaries[Salaries>84496.5]
arr2

array([  87877,   85051,   94868,   98446,   99658,   89224,   90947,
       3113638])

In [125]:
len(Salaries<52963.25)

30