### creating array using numpy

In [2]:
import numpy as na

In [4]:
array1 =na.array([1,23,45,67,98,89])
type(array1)

numpy.ndarray

In [6]:
# array from list
list1 = [1,2,3,4,5,6,7,98]
na.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7, 98])

In [7]:
# array from tuple
list2 = (1,2,3,4,5,6,7,89)
na.array(list2)

array([ 1,  2,  3,  4,  5,  6,  7, 89])

### creating 1D array using numpy with 12 postive integers as arr1

In [8]:
arr1 = na.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [9]:
arr1.dtype # returns integer data type

dtype('int32')

In [10]:
arr1.ndim # 1 returns as 1-D array

1

### creating 1-D array with 20 elements from 0 to 12 integers using linspace 

In [14]:
array1 = na.linspace(0,12,20)

In [15]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### attributes of array1 and array2

In [18]:
array1 = na.array([1,2,3,45,67,98,89])
array2 = na.array([9.8,8.9,8.8,9.9,9.0,8.0])

In [19]:
array1.dtype # retunrs the array data type

dtype('int32')

In [20]:
array2.dtype

dtype('float64')

In [22]:
array1.itemsize # retunrs the memory occupied by each value

4

In [23]:
array2.itemsize

8

In [26]:
array1.mean() # returns mean of the array

43.57142857142857

In [27]:
array2.mean()

9.066666666666668

In [29]:
array1.nbytes # total memory occupied by the array

28

In [30]:
array2.nbytes 

48

In [34]:
array1.size # size of the array

7

In [39]:
array2.size

6

In [48]:
array1.astype("float64") # can convert the datatype fo the array

array([ 1.,  2.,  3., 45., 67., 98., 89.])

In [49]:
array2.astype("int64")

array([9, 8, 8, 9, 9, 8], dtype=int64)

### measure and describe the data for array1 and array2 using numpy

In [59]:
array1

array([ 1,  2,  3, 45, 67, 89, 98])

In [61]:
# measure of central tendency
array1.mean() # mean of array

43.57142857142857

In [62]:
array2

array([9.8, 8.9, 8.8, 9.9, 9. , 8. ])

In [64]:
array2.mean()

9.066666666666668

In [67]:
na.median(array1) # median

45.0

In [68]:
na.median(array2)

8.95

In [70]:
# to find range of array
na.min(array1)
na.max(array1)
range1 = na.max(array1) - na.min(array1)
range1

97

In [72]:
na.max(array2)
na.min(array2)
range2 = na.max(array2) - na.min(array2)
range2

1.9000000000000004

In [74]:
# to find the outlier we use IQR
q1 = na.percentile(array1,25)
q3 = na.percentile(array1,75)
IQR = q3 - q1
IQR

75.5

In [75]:
lower = q1 - (1.5*IQR)
lower

-110.75

In [76]:
upper = q3 + (1.5*IQR)
upper

191.25

In [77]:
array1[array1>upper] # there is no outlier

array([], dtype=int32)

In [79]:
array1[array1<lower] #  there is no outlier

array([], dtype=int32)