In [2]:
import numpy as na

In [35]:
a = na.genfromtxt(r"C:\Users\91832\Downloads\Iris_clean_-_Copy.csv",dtype = 'float16',delimiter = ',')
a


array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [42]:
a = a[1:]

In [43]:
a

array([[5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000e-01],
       [5.699e+00, 3.801e+00, 1.700e+00, 3.000

In [44]:
na.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
 

In [45]:
b = na.nanmedian(a)

In [46]:
b

3.2

In [48]:
b = na.where(na.isnan(a),b,a)
b

array([[5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00, 3.199e+00, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00, 3.199e+00, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01, 3.199e+00, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000e-01],
       [5.699e+00, 3.801e+00, 1.700e+00, 3.000

In [13]:
(b<2) | (b>6) | (b<1) | (b>4)

array([[ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
 

In [53]:
sepal_width = b[:,1:2]
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  3.2],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  3.2],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [57]:
sepal_width_mean = na.median(sepal_width)
sepal_width_mean

3.0

In [54]:
(sepal_width>2)|(sepal_width<0)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [58]:
sepal_width = na.where((sepal_width>2)|(sepal_width<0),sepal_width_mean,sepal_width)
sepal_width

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],

In [60]:
petal_length = b[:,2:3]
petal_length

array([[ 1.4],
       [ 1.4],
       [ 1.3],
       [ 1.5],
       [ 1.4],
       [ 1.7],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 3.2],
       [ 1.5],
       [ 1.6],
       [ 1.4],
       [ 1.1],
       [ 1.2],
       [ 1.5],
       [ 1.3],
       [ 1.4],
       [ 1.7],
       [ 1.5],
       [ 1.7],
       [ 1.5],
       [ 1. ],
       [ 1.7],
       [ 1.9],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.4],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.2],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [13. ],
       [ 1.3],
       [ 1.6],
       [ 1.9],
       [ 1.4],
       [ 1.6],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 4.7],
       [ 4.5],
       [ 4.9],
       [ 4. ],
       [ 4.6],
       [ 4.5],
       [ 4.7],
       [ 3.3],
       [ 4.6],
       [ 3.9],
       [ 3.5],
       [ 4.2],
       [ 4. ],
       [ 4.7],
       [ 3.6],
       [ 4.4],
       [ 4

In [61]:
(petal_length >4) | (petal_length<0)

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [

In [62]:
petal_length_median = na.median(petal_length)
petal_length_median

4.5

In [63]:
petal_length = na.where((petal_length >4) | (petal_length<0),petal_length_median,petal_length)
petal_length

array([[1.4],
       [1.4],
       [1.3],
       [1.5],
       [1.4],
       [1.7],
       [1.4],
       [1.5],
       [1.4],
       [3.2],
       [1.5],
       [1.6],
       [1.4],
       [1.1],
       [1.2],
       [1.5],
       [1.3],
       [1.4],
       [1.7],
       [1.5],
       [1.7],
       [1.5],
       [1. ],
       [1.7],
       [1.9],
       [1.6],
       [1.6],
       [1.5],
       [1.4],
       [1.6],
       [1.6],
       [1.5],
       [1.5],
       [1.4],
       [1.5],
       [1.2],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [4.5],
       [1.3],
       [1.6],
       [1.9],
       [1.4],
       [1.6],
       [1.4],
       [1.5],
       [1.4],
       [4.5],
       [4.5],
       [4.5],
       [4. ],
       [4.5],
       [4.5],
       [4.5],
       [3.3],
       [4.5],
       [3.9],
       [3.5],
       [4.5],
       [4. ],
       [4.5],
       [3.6],
       [4.5],
       [4.5],
       [4.5],
       [4.5],
       [3.9],
       [4.5],
      

In [65]:
petal_width = b[:,3:4]
petal_width

array([[2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [1.020e+01],
       [2.000e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [1.010e+01],
       [9.998e-02],
       [2.000e-01],
       [3.999e-01],
       [3.999e-01],
       [3.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [5.000e-01],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [1.102e+02],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [9.998e-02],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [6.001e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],


In [66]:
(petal_width >1.3) | (petal_width < 0)

array([[False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [

In [67]:
petal_width_median = na.median(petal_width)
petal_width_median

1.5

In [68]:
petal_width = na.where((petal_width >1.3) | (petal_width < 0),petal_width_median,petal_width)
petal_width

array([[0.2],
       [0.2],
       [0.2],
       [1.5],
       [0.2],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [1.5],
       [0.1],
       [0.2],
       [0.4],
       [0.4],
       [0.3],
       [0.3],
       [0.3],
       [0.2],
       [0.4],
       [0.2],
       [0.5],
       [0.2],
       [0.2],
       [0.4],
       [0.2],
       [1.5],
       [0.2],
       [0.2],
       [0.4],
       [0.1],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.1],
       [0.2],
       [0.2],
       [0.3],
       [0.3],
       [0.2],
       [0.6],
       [0.4],
       [0.3],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [1.5],
       [1.5],
       [1.5],
       [1.3],
       [1.5],
       [1.3],
       [1.5],
       [1.5],
       [1.3],
       [1.5],
       [1. ],
       [1.5],
       [1. ],
       [1.5],
       [1.3],
       [1.5],
       [1.5],
       [1. ],
       [1.5],
       [1.1],
       [1.5],
      

In [84]:
sepal_length = b[:,:1]
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [85]:
len(sepal_length)

165

In [88]:
(sepal_length >6) | (sepal_length <0)

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [91]:
sepal_length_median = na.median(sepal_length)
sepal_length_median

5.8

In [92]:
sepal_length = na.where((sepal_length >6) | (sepal_length <0),sepal_length_median,sepal_length)
sepal_length

array([[5.1],
       [4.9],
       [4.7],
       [4.6],
       [5.8],
       [5.4],
       [4.6],
       [5. ],
       [4.4],
       [4.9],
       [5.4],
       [4.8],
       [4.8],
       [4.3],
       [5.8],
       [5.7],
       [5.8],
       [5.1],
       [5.7],
       [5.1],
       [5.4],
       [5.1],
       [4.6],
       [5.1],
       [4.8],
       [5. ],
       [5. ],
       [5.2],
       [5.2],
       [4.7],
       [4.8],
       [5.4],
       [5.2],
       [5.5],
       [4.9],
       [5. ],
       [5.5],
       [4.9],
       [4.4],
       [5.1],
       [5. ],
       [4.5],
       [4.4],
       [5. ],
       [5.1],
       [4.8],
       [5.1],
       [4.6],
       [5.3],
       [5. ],
       [5.8],
       [5.8],
       [5.8],
       [5.5],
       [5.8],
       [5.7],
       [5.8],
       [4.9],
       [5.8],
       [5.2],
       [5. ],
       [5.9],
       [6. ],
       [5.8],
       [5.6],
       [5.8],
       [5.6],
       [5.8],
       [5.8],
       [5.6],
       [5.9],
      

In [93]:
len(sepal_length)

165

In [94]:
iris_flower = na.hstack([sepal_length,sepal_width])

In [95]:
iris_flower

array([[5.1, 3. ],
       [4.9, 3. ],
       [4.7, 3. ],
       [4.6, 3. ],
       [5.8, 3. ],
       [5.4, 3. ],
       [4.6, 3. ],
       [5. , 3. ],
       [4.4, 3. ],
       [4.9, 3. ],
       [5.4, 3. ],
       [4.8, 3. ],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 3. ],
       [5.7, 3. ],
       [5.8, 3. ],
       [5.1, 3. ],
       [5.7, 3. ],
       [5.1, 3. ],
       [5.4, 3. ],
       [5.1, 3. ],
       [4.6, 3. ],
       [5.1, 3. ],
       [4.8, 3. ],
       [5. , 3. ],
       [5. , 3. ],
       [5.2, 3. ],
       [5.2, 3. ],
       [4.7, 3. ],
       [4.8, 3. ],
       [5.4, 3. ],
       [5.2, 3. ],
       [5.5, 3. ],
       [4.9, 3. ],
       [5. , 3. ],
       [5.5, 3. ],
       [4.9, 3. ],
       [4.4, 3. ],
       [5.1, 3. ],
       [5. , 3. ],
       [4.5, 3. ],
       [4.4, 3. ],
       [5. , 3. ],
       [5.1, 3. ],
       [4.8, 3. ],
       [5.1, 3. ],
       [4.6, 3. ],
       [5.3, 3. ],
       [5. , 3. ],
       [5.8, 3. ],
       [5.8, 3. ],
       [5.8,

In [96]:
iris_flower = na.hstack([iris_flower,petal_length])

In [97]:
iris_flower

array([[5.1, 3. , 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3. , 1.3],
       [4.6, 3. , 1.5],
       [5.8, 3. , 1.4],
       [5.4, 3. , 1.7],
       [4.6, 3. , 1.4],
       [5. , 3. , 1.5],
       [4.4, 3. , 1.4],
       [4.9, 3. , 3.2],
       [5.4, 3. , 1.5],
       [4.8, 3. , 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 3. , 1.2],
       [5.7, 3. , 1.5],
       [5.8, 3. , 1.3],
       [5.1, 3. , 1.4],
       [5.7, 3. , 1.7],
       [5.1, 3. , 1.5],
       [5.4, 3. , 1.7],
       [5.1, 3. , 1.5],
       [4.6, 3. , 1. ],
       [5.1, 3. , 1.7],
       [4.8, 3. , 1.9],
       [5. , 3. , 1.6],
       [5. , 3. , 1.6],
       [5.2, 3. , 1.5],
       [5.2, 3. , 1.4],
       [4.7, 3. , 1.6],
       [4.8, 3. , 1.6],
       [5.4, 3. , 1.5],
       [5.2, 3. , 1.5],
       [5.5, 3. , 1.4],
       [4.9, 3. , 1.5],
       [5. , 3. , 1.2],
       [5.5, 3. , 1.3],
       [4.9, 3. , 1.5],
       [4.4, 3. , 1.3],
       [5.1, 3. , 1.5],
       [5. , 3. , 1.3],
       [4.5, 3. 

In [99]:
iris_flower = na.hstack([iris_flower,petal_width])
iris_flower

array([[5.1, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3. , 1.3, 0.2],
       [4.6, 3. , 1.5, 1.5],
       [5.8, 3. , 1.4, 0.2],
       [5.4, 3. , 1.7, 0.4],
       [4.6, 3. , 1.4, 0.3],
       [5. , 3. , 1.5, 0.2],
       [4.4, 3. , 1.4, 0.2],
       [4.9, 3. , 3.2, 0.1],
       [5.4, 3. , 1.5, 0.2],
       [4.8, 3. , 1.6, 0.2],
       [4.8, 3. , 1.4, 1.5],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 3. , 1.2, 0.2],
       [5.7, 3. , 1.5, 0.4],
       [5.8, 3. , 1.3, 0.4],
       [5.1, 3. , 1.4, 0.3],
       [5.7, 3. , 1.7, 0.3],
       [5.1, 3. , 1.5, 0.3],
       [5.4, 3. , 1.7, 0.2],
       [5.1, 3. , 1.5, 0.4],
       [4.6, 3. , 1. , 0.2],
       [5.1, 3. , 1.7, 0.5],
       [4.8, 3. , 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3. , 1.6, 0.4],
       [5.2, 3. , 1.5, 0.2],
       [5.2, 3. , 1.4, 1.5],
       [4.7, 3. , 1.6, 0.2],
       [4.8, 3. , 1.6, 0.2],
       [5.4, 3. , 1.5, 0.4],
       [5.2, 3. , 1.5, 0.1],
       [5.5, 3. , 1.4, 0.2],
       [4.9, 3

In [100]:
iris_flower.astype("int16")

array([[5, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 1],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 3, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 1],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 1],
       [4, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 4, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3, 1, 0],
       [5, 3, 1, 0],
       [4, 3,

In [101]:
sepal_length.mean()

5.453

In [107]:
na.sort(sepal_width)

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],

In [108]:
sepal_width.mean()

2.994

In [109]:
na.median(sepal_width)

3.0

In [110]:
sepal_length.mean()

5.453

In [111]:
na.median(sepal_length)

5.8

In [112]:
sepal_length.max()

6.0

In [113]:
sepal_length.min()

3.2

In [114]:
range = sepal_length.max() - sepal_length.min()
range

2.8

In [115]:
sepal_width.max()

3.0

In [116]:
sepal_width.min()

2.0

In [117]:
range = sepal_width.max() - sepal_width.min()
range

1.0

In [135]:
q1 = na.quantile(sepal_length,0.25)

In [136]:
q1

5.1015625

In [137]:
q3 = na.quantile(sepal_length,0.75)
q3

5.80078125

In [138]:
IQR1 = q3 - q1
IQR1

0.69921875

In [139]:
q1 = na.quantile(sepal_width,0.25)
q1

3.0

In [140]:
q3 = na.quantile(sepal_width,0.75)
q3

3.0

In [141]:
IQR2 = q3 - q1
IQR2

0.0

In [142]:
lower = q1 - (1.5*IQR1)
lower

1.951171875

In [143]:
upper = q3 + (1.5*IQR1)
upper

4.048828125

In [151]:
cleaned_iris = na.savetxt("cleaned_iris.txt",iris_flower)

In [152]:
na.loadtxt("cleaned_iris.txt")

array([[5.1015625 , 3.        , 1.40039062, 0.19995117],
       [4.8984375 , 3.        , 1.40039062, 0.19995117],
       [4.69921875, 3.        , 1.29980469, 0.19995117],
       [4.6015625 , 3.        , 1.5       , 1.5       ],
       [5.80078125, 3.        , 1.40039062, 0.19995117],
       [5.3984375 , 3.        , 1.70019531, 0.39990234],
       [4.6015625 , 3.        , 1.40039062, 0.30004883],
       [5.        , 3.        , 1.5       , 0.19995117],
       [4.3984375 , 3.        , 1.40039062, 0.19995117],
       [4.8984375 , 3.        , 3.19921875, 0.09997559],
       [5.3984375 , 3.        , 1.5       , 0.19995117],
       [4.80078125, 3.        , 1.59960938, 0.19995117],
       [4.80078125, 3.        , 1.40039062, 1.5       ],
       [4.30078125, 3.        , 1.09960938, 0.09997559],
       [5.80078125, 3.        , 1.20019531, 0.19995117],
       [5.69921875, 3.        , 1.5       , 0.39990234],
       [5.80078125, 3.        , 1.29980469, 0.39990234],
       [5.1015625 , 3.        ,

In [153]:
iris_cleaned = na.save("cleaned_irisflower.npy",iris_flower)

In [154]:
na.load("cleaned_irisflower.npy")

array([[5.1, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3. , 1.3, 0.2],
       [4.6, 3. , 1.5, 1.5],
       [5.8, 3. , 1.4, 0.2],
       [5.4, 3. , 1.7, 0.4],
       [4.6, 3. , 1.4, 0.3],
       [5. , 3. , 1.5, 0.2],
       [4.4, 3. , 1.4, 0.2],
       [4.9, 3. , 3.2, 0.1],
       [5.4, 3. , 1.5, 0.2],
       [4.8, 3. , 1.6, 0.2],
       [4.8, 3. , 1.4, 1.5],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 3. , 1.2, 0.2],
       [5.7, 3. , 1.5, 0.4],
       [5.8, 3. , 1.3, 0.4],
       [5.1, 3. , 1.4, 0.3],
       [5.7, 3. , 1.7, 0.3],
       [5.1, 3. , 1.5, 0.3],
       [5.4, 3. , 1.7, 0.2],
       [5.1, 3. , 1.5, 0.4],
       [4.6, 3. , 1. , 0.2],
       [5.1, 3. , 1.7, 0.5],
       [4.8, 3. , 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3. , 1.6, 0.4],
       [5.2, 3. , 1.5, 0.2],
       [5.2, 3. , 1.4, 1.5],
       [4.7, 3. , 1.6, 0.2],
       [4.8, 3. , 1.6, 0.2],
       [5.4, 3. , 1.5, 0.4],
       [5.2, 3. , 1.5, 0.1],
       [5.5, 3. , 1.4, 0.2],
       [4.9, 3