# pandas Series
1. Create pandas series with different `data types` in `different ways`
2. Find the `attributes` of Series of [10,30,40,1,3,6,14,18,23] with index starts from `100`
3. create salaries of `30 employee salaries randomly from 30000-90000` then `measure and describe` the data using pandas series.
4. What are the `similaraties` and `differences` between pandas series and nnumpy array.Prove it with code.
5. create pandas series with ranges from 100 to 150 then apply indexing and slicing on it.

### creating pandas series

In [1]:
# from list
a = list(range(10,90,9))
a

[10, 19, 28, 37, 46, 55, 64, 73, 82]

In [37]:
import pandas as pd
import numpy as na

In [7]:
a = pd.Series(a)
a

0    10
1    19
2    28
3    37
4    46
5    55
6    64
7    73
8    82
dtype: int64

In [8]:
#from tuple
b = (1,2,3,4,5,6,7,8,9)
pd.Series(b)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [9]:
#from array
arr = na.random.randint(89,98,9)

In [12]:
arr

array([96, 97, 96, 90, 92, 91, 94, 97, 91])

In [11]:
pd.Series(arr)

0    96
1    97
2    96
3    90
4    92
5    91
6    94
7    97
8    91
dtype: int32

In [13]:
# from dictionary
dict1 = {"A":'AISH',"B":'ANK',"C":'VAMSHI'}

In [14]:
pd.Series(dict1)

A      AISH
B       ANK
C    VAMSHI
dtype: object

In [18]:
arr = na.array([10,30,40,1,3,6,14,18,23])

In [23]:
na = pd.Series((arr),index = list(range(100,109)))
na

100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int32

### Attributes

In [24]:
na.info()

<class 'pandas.core.series.Series'>
Index: 9 entries, 100 to 108
Series name: None
Non-Null Count  Dtype
--------------  -----
9 non-null      int32
dtypes: int32(1)
memory usage: 108.0 bytes


In [26]:
na.describe()

count     9.000000
mean     16.111111
std      13.033078
min       1.000000
25%       6.000000
50%      14.000000
75%      23.000000
max      40.000000
dtype: float64

In [27]:
na.head()

100    10
101    30
102    40
103     1
104     3
dtype: int32

In [28]:
na.tail()

104     3
105     6
106    14
107    18
108    23
dtype: int32

In [30]:
na.dtype

dtype('int32')

In [31]:
na.memory_usage()

108

In [32]:
na.where(na<9)

100    NaN
101    NaN
102    NaN
103    1.0
104    3.0
105    6.0
106    NaN
107    NaN
108    NaN
dtype: float64

In [33]:
na.ndim

1

In [34]:
na.size

9

In [40]:
arr = na.random.randint(30000,90000,30)
a = pd.Series(arr)
a


0     70992
1     51684
2     33689
3     53121
4     77480
5     64671
6     85666
7     67369
8     76384
9     46914
10    68939
11    57028
12    79805
13    72168
14    73533
15    66019
16    61307
17    89989
18    64492
19    81017
20    78787
21    39890
22    83428
23    73259
24    61772
25    50962
26    37027
27    45801
28    83102
29    85584
dtype: int32

### measure and describe

In [41]:
a.mean()

66062.63333333333

In [42]:
a.median()

68154.0

In [43]:
a.mode()

0     33689
1     37027
2     39890
3     45801
4     46914
5     50962
6     51684
7     53121
8     57028
9     61307
10    61772
11    64492
12    64671
13    66019
14    67369
15    68939
16    70992
17    72168
18    73259
19    73533
20    76384
21    77480
22    78787
23    79805
24    81017
25    83102
26    83428
27    85584
28    85666
29    89989
dtype: int32

In [45]:
a.min()

33689

In [46]:
a.max()

89989

In [47]:
range = a.max()-a.min()
range

56300

In [48]:
a.var()

241476540.791954

In [49]:
a.std()

15539.515461942628

In [50]:
a.quantile(0.25)

54097.75

In [51]:
a.quantile(0.75)

78460.25

In [52]:
IQR = a.quantile(0.75) - a.quantile(0.25)
IQR

24362.5

### similarites numpy and series-pandas

In [58]:
# both provide 1-D array and numerical values
numpy_arr = na.array([1,2,3,4,5,6,7,8,9])
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
numpy_arr.ndim

1

In [60]:
pandas = pd.Series(numpy_arr)

In [61]:
pandas

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

In [62]:
pandas.ndim

1

### Differences

In [63]:
# numpy cannot deal with text data where as pandas series can
# pandas is index based library where as numpy is not index based
numpy_arr1 = na.array(['A','ish','A','NK'])

In [64]:
numpy_arr1

array(['A', 'ish', 'A', 'NK'], dtype='<U3')

In [70]:
numpy_arr1.dtype

dtype('<U3')

In [71]:
pandas = pd.Series(numpy_arr1)
pandas

0      A
1    ish
2      A
3     NK
dtype: object

In [72]:
pandas.dtype

dtype('O')

In [87]:
a = na.arange(100,151)

In [88]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [89]:
a = pd.Series(a)

In [90]:
a

0     100
1     101
2     102
3     103
4     104
5     105
6     106
7     107
8     108
9     109
10    110
11    111
12    112
13    113
14    114
15    115
16    116
17    117
18    118
19    119
20    120
21    121
22    122
23    123
24    124
25    125
26    126
27    127
28    128
29    129
30    130
31    131
32    132
33    133
34    134
35    135
36    136
37    137
38    138
39    139
40    140
41    141
42    142
43    143
44    144
45    145
46    146
47    147
48    148
49    149
50    150
dtype: int32

### indexing and slicing

In [91]:
a[0]

100

In [92]:
a[1:3]

1    101
2    102
dtype: int32

In [93]:
a[50::-1]

50    150
49    149
48    148
47    147
46    146
45    145
44    144
43    143
42    142
41    141
40    140
39    139
38    138
37    137
36    136
35    135
34    134
33    133
32    132
31    131
30    130
29    129
28    128
27    127
26    126
25    125
24    124
23    123
22    122
21    121
20    120
19    119
18    118
17    117
16    116
15    115
14    114
13    113
12    112
11    111
10    110
9     109
8     108
7     107
6     106
5     105
4     104
3     103
2     102
1     101
0     100
dtype: int32

In [97]:
a[40:20:-2]

40    140
38    138
36    136
34    134
32    132
30    130
28    128
26    126
24    124
22    122
dtype: int32